// V2 vault ABI (sourced from curator-scripts/src/abis/)

export const vaultV2Abi = [
  // ===== Read Functions =====
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "curator",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "timelock",
    stateMutability: "view",
    inputs: [{ name: "selector", type: "bytes4" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "executableAt",
    stateMutability: "view",
    inputs: [{ name: "data", type: "bytes" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalAssets",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "performanceFee",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "managementFee",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "allocation",
    stateMutability: "view",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "absoluteCap",
    stateMutability: "view",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "relativeCap",
    stateMutability: "view",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "name",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "symbol",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "totalSupply",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "asset",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "maxRate",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "isSentinel",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },

  // ===== Events =====
  {
    type: "event",
    name: "Submit",
    inputs: [
      { name: "selector", type: "bytes4", indexed: true },
      { name: "data", type: "bytes", indexed: false },
      { name: "executableAt", type: "uint256", indexed: false },
    ],
  },

  // ===== Write Functions =====
  {
    type: "function",
    name: "allocate",
    stateMutability: "nonpayable",
    inputs: [
      { name: "adapter", type: "address" },
      { name: "data", type: "bytes" },
      { name: "assets", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "deallocate",
    stateMutability: "nonpayable",
    inputs: [
      { name: "adapter", type: "address" },
      { name: "data", type: "bytes" },
      { name: "assets", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "increaseAbsoluteCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "idData", type: "bytes" },
      { name: "newAbsoluteCap", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "decreaseAbsoluteCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "idData", type: "bytes" },
      { name: "newAbsoluteCap", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "increaseRelativeCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "idData", type: "bytes" },
      { name: "newRelativeCap", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "decreaseRelativeCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "idData", type: "bytes" },
      { name: "newRelativeCap", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "addAdapter",
    stateMutability: "nonpayable",
    inputs: [{ name: "adapter", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "removeAdapter",
    stateMutability: "nonpayable",
    inputs: [{ name: "adapter", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setPerformanceFee",
    stateMutability: "nonpayable",
    inputs: [{ name: "newFee", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setManagementFee",
    stateMutability: "nonpayable",
    inputs: [{ name: "newFee", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setMaxRate",
    stateMutability: "nonpayable",
    inputs: [{ name: "newMaxRate", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setLiquidityAdapterAndData",
    stateMutability: "nonpayable",
    inputs: [
      { name: "liquidityAdapter", type: "address" },
      { name: "liquidityData", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "submit",
    stateMutability: "nonpayable",
    inputs: [{ name: "data", type: "bytes" }],
    outputs: [],
  },
  {
    type: "function",
    name: "revoke",
    stateMutability: "nonpayable",
    inputs: [{ name: "data", type: "bytes" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setOwner",
    stateMutability: "nonpayable",
    inputs: [{ name: "newOwner", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setCurator",
    stateMutability: "nonpayable",
    inputs: [{ name: "newCurator", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setIsSentinel",
    stateMutability: "nonpayable",
    inputs: [
      { name: "account", type: "address" },
      { name: "newIsSentinel", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setName",
    stateMutability: "nonpayable",
    inputs: [{ name: "newName", type: "string" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setSymbol",
    stateMutability: "nonpayable",
    inputs: [{ name: "newSymbol", type: "string" }],
    outputs: [],
  },
  {
    type: "function",
    name: "multicall",
    stateMutability: "nonpayable",
    inputs: [{ name: "data", type: "bytes[]" }],
    outputs: [],
  },
] as const;
