// V2 vault ABI (sourced from curator-scripts/src/abis/)

export const vaultV2Abi = [
  // ===== Read Functions =====
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "liquidityAdapter",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "liquidityData",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bytes" }],
  },
  {
    type: "function",
    name: "curator",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "timelock",
    stateMutability: "view",
    inputs: [{ name: "selector", type: "bytes4" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "sendAssetsGate",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "receiveAssetsGate",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "receiveSharesGate",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "sendSharesGate",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "canSendAssets",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "executableAt",
    stateMutability: "view",
    inputs: [{ name: "data", type: "bytes" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalAssets",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "performanceFee",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "managementFee",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "allocation",
    stateMutability: "view",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "absoluteCap",
    stateMutability: "view",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "relativeCap",
    stateMutability: "view",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "name",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "symbol",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "totalSupply",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "asset",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "maxRate",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "isSentinel",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "isAllocator",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },

  // ===== Events =====
  {
    type: "event",
    name: "Submit",
    inputs: [
      { name: "selector", type: "bytes4", indexed: true },
      { name: "data", type: "bytes", indexed: false },
      { name: "executableAt", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DecreaseAbsoluteCap",
    inputs: [
      { name: "sender", type: "address", indexed: true },
      { name: "id", type: "bytes32", indexed: true },
      { name: "idData", type: "bytes", indexed: false },
      { name: "newAbsoluteCap", type: "uint256", indexed: false },
    ],
  },
  {
    type: "event",
    name: "DecreaseRelativeCap",
    inputs: [
      { name: "sender", type: "address", indexed: true },
      { name: "id", type: "bytes32", indexed: true },
      { name: "idData", type: "bytes", indexed: false },
      { name: "newRelativeCap", type: "uint256", indexed: false },
    ],
  },

  // ===== Write Functions =====
  {
    type: "function",
    name: "allocate",
    stateMutability: "nonpayable",
    inputs: [
      { name: "adapter", type: "address" },
      { name: "data", type: "bytes" },
      { name: "assets", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "deallocate",
    stateMutability: "nonpayable",
    inputs: [
      { name: "adapter", type: "address" },
      { name: "data", type: "bytes" },
      { name: "assets", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "increaseAbsoluteCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "idData", type: "bytes" },
      { name: "newAbsoluteCap", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "decreaseAbsoluteCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "idData", type: "bytes" },
      { name: "newAbsoluteCap", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "increaseRelativeCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "idData", type: "bytes" },
      { name: "newRelativeCap", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "decreaseRelativeCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "idData", type: "bytes" },
      { name: "newRelativeCap", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "addAdapter",
    stateMutability: "nonpayable",
    inputs: [{ name: "adapter", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "removeAdapter",
    stateMutability: "nonpayable",
    inputs: [{ name: "adapter", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setPerformanceFee",
    stateMutability: "nonpayable",
    inputs: [{ name: "newFee", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setManagementFee",
    stateMutability: "nonpayable",
    inputs: [{ name: "newFee", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setMaxRate",
    stateMutability: "nonpayable",
    inputs: [{ name: "newMaxRate", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setSendAssetsGate",
    stateMutability: "nonpayable",
    inputs: [{ name: "newSendAssetsGate", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setLiquidityAdapterAndData",
    stateMutability: "nonpayable",
    inputs: [
      { name: "liquidityAdapter", type: "address" },
      { name: "liquidityData", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "submit",
    stateMutability: "nonpayable",
    inputs: [{ name: "data", type: "bytes" }],
    outputs: [],
  },
  {
    type: "function",
    name: "revoke",
    stateMutability: "nonpayable",
    inputs: [{ name: "data", type: "bytes" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setOwner",
    stateMutability: "nonpayable",
    inputs: [{ name: "newOwner", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setCurator",
    stateMutability: "nonpayable",
    inputs: [{ name: "newCurator", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setIsSentinel",
    stateMutability: "nonpayable",
    inputs: [
      { name: "account", type: "address" },
      { name: "newIsSentinel", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setName",
    stateMutability: "nonpayable",
    inputs: [{ name: "newName", type: "string" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setSymbol",
    stateMutability: "nonpayable",
    inputs: [{ name: "newSymbol", type: "string" }],
    outputs: [],
  },
  {
    type: "function",
    name: "multicall",
    stateMutability: "nonpayable",
    inputs: [{ name: "data", type: "bytes[]" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setIsAllocator",
    stateMutability: "nonpayable",
    inputs: [
      { name: "account", type: "address" },
      { name: "newIsAllocator", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setReceiveSharesGate",
    stateMutability: "nonpayable",
    inputs: [{ name: "newReceiveSharesGate", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setSendSharesGate",
    stateMutability: "nonpayable",
    inputs: [{ name: "newSendSharesGate", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setReceiveAssetsGate",
    stateMutability: "nonpayable",
    inputs: [{ name: "newReceiveAssetsGate", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setAdapterRegistry",
    stateMutability: "nonpayable",
    inputs: [{ name: "newAdapterRegistry", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setPerformanceFeeRecipient",
    stateMutability: "nonpayable",
    inputs: [{ name: "newFeeRecipient", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setManagementFeeRecipient",
    stateMutability: "nonpayable",
    inputs: [{ name: "newFeeRecipient", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "increaseTimelock",
    stateMutability: "nonpayable",
    inputs: [
      { name: "selector", type: "bytes4" },
      { name: "newDuration", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "decreaseTimelock",
    stateMutability: "nonpayable",
    inputs: [
      { name: "selector", type: "bytes4" },
      { name: "newDuration", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "abdicate",
    stateMutability: "nonpayable",
    inputs: [{ name: "selector", type: "bytes4" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setForceDeallocatePenalty",
    stateMutability: "nonpayable",
    inputs: [
      { name: "adapter", type: "address" },
      { name: "newForceDeallocatePenalty", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "forceDeallocate",
    stateMutability: "nonpayable",
    inputs: [
      { name: "adapter", type: "address" },
      { name: "data", type: "bytes" },
      { name: "assets", type: "uint256" },
      { name: "onBehalf", type: "address" },
    ],
    outputs: [{ name: "", type: "uint256" }],
  },

  // Vault V2 ErrorsLib + adapter / Morpho Blue errors that bubble through allocate.
  { type: "error", name: "Abdicated", inputs: [] },
  { type: "error", name: "AbsoluteCapExceeded", inputs: [] },
  { type: "error", name: "AbsoluteCapNotDecreasing", inputs: [] },
  { type: "error", name: "AbsoluteCapNotIncreasing", inputs: [] },
  { type: "error", name: "ApproveReturnedFalse", inputs: [] },
  { type: "error", name: "ApproveReverted", inputs: [] },
  { type: "error", name: "AutomaticallyTimelocked", inputs: [] },
  { type: "error", name: "CannotReceiveShares", inputs: [] },
  { type: "error", name: "CannotReceiveAssets", inputs: [] },
  { type: "error", name: "CannotSendShares", inputs: [] },
  { type: "error", name: "CannotSendAssets", inputs: [] },
  { type: "error", name: "CapExceeded", inputs: [] },
  { type: "error", name: "CastOverflow", inputs: [] },
  { type: "error", name: "DataAlreadyPending", inputs: [] },
  { type: "error", name: "DataNotTimelocked", inputs: [] },
  { type: "error", name: "FeeInvariantBroken", inputs: [] },
  { type: "error", name: "FeeTooHigh", inputs: [] },
  { type: "error", name: "InvalidSigner", inputs: [] },
  { type: "error", name: "MaxRateTooHigh", inputs: [] },
  { type: "error", name: "NoCode", inputs: [] },
  { type: "error", name: "NotAdapter", inputs: [] },
  { type: "error", name: "NotInAdapterRegistry", inputs: [] },
  { type: "error", name: "PenaltyTooHigh", inputs: [] },
  { type: "error", name: "PermitDeadlineExpired", inputs: [] },
  { type: "error", name: "RelativeCapAboveOne", inputs: [] },
  { type: "error", name: "RelativeCapExceeded", inputs: [] },
  { type: "error", name: "RelativeCapNotDecreasing", inputs: [] },
  { type: "error", name: "RelativeCapNotIncreasing", inputs: [] },
  { type: "error", name: "TimelockNotDecreasing", inputs: [] },
  { type: "error", name: "TimelockNotExpired", inputs: [] },
  { type: "error", name: "TimelockNotIncreasing", inputs: [] },
  { type: "error", name: "TransferFromReturnedFalse", inputs: [] },
  { type: "error", name: "TransferFromReverted", inputs: [] },
  { type: "error", name: "TransferReturnedFalse", inputs: [] },
  { type: "error", name: "TransferReverted", inputs: [] },
  { type: "error", name: "Unauthorized", inputs: [] },
  { type: "error", name: "ZeroAbsoluteCap", inputs: [] },
  { type: "error", name: "ZeroAddress", inputs: [] },
  { type: "error", name: "ZeroAllocation", inputs: [] },
  { type: "error", name: "InvalidData", inputs: [] },
  { type: "error", name: "LoanAssetMismatch", inputs: [] },
  { type: "error", name: "IrmMismatch", inputs: [] },
  { type: "error", name: "SharePriceAboveOne", inputs: [] },
  { type: "error", name: "InsufficientLiquidity", inputs: [] },
  { type: "error", name: "MarketNotCreated", inputs: [] },
] as const;

/** Vault V2 Blue Public Allocator — view fragment for curator Caps UI. */
export const vaultV2BluePublicAllocatorAbi = [
  {
    type: 'function',
    name: 'absoluteCap',
    stateMutability: 'view',
    inputs: [
      { name: 'vault', type: 'address' },
      { name: 'id', type: 'bytes32' },
    ],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'canPullFromMarket',
    stateMutability: 'view',
    inputs: [
      { name: 'vault', type: 'address' },
      { name: 'id', type: 'bytes32' },
    ],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function',
    name: 'vaultData',
    stateMutability: 'view',
    inputs: [{ name: 'vault', type: 'address' }],
    outputs: [
      { name: 'canPullFromIdle', type: 'bool' },
      { name: 'penalty', type: 'uint64' },
    ],
  },
] as const;
