// Complete ABIs for Morpho V1 (MetaMorpho) and V2 vaults
// Sourced from curator-scripts/src/abis/

export const metaMorphoV1Abi = [
  // ===== Read Functions =====
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "curator",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "guardian",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "fee",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "feeRecipient",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "timelock",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "asset",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "totalAssets",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalSupply",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "name",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "symbol",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "decimals",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint8" }],
  },
  {
    type: "function",
    name: "MORPHO",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "supplyQueueLength",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "supplyQueue",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "withdrawQueueLength",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "withdrawQueue",
    stateMutability: "view",
    inputs: [{ name: "", type: "uint256" }],
    outputs: [{ name: "", type: "bytes32" }],
  },
  {
    type: "function",
    name: "config",
    stateMutability: "view",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [
      { name: "cap", type: "uint184" },
      { name: "enabled", type: "bool" },
      { name: "removableAt", type: "uint64" },
    ],
  },
  {
    type: "function",
    name: "pendingCap",
    stateMutability: "view",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [
      { name: "value", type: "uint192" },
      { name: "validAt", type: "uint64" },
    ],
  },
  {
    type: "function",
    name: "pendingTimelock",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "value", type: "uint192" },
      { name: "validAt", type: "uint64" },
    ],
  },
  {
    type: "function",
    name: "pendingGuardian",
    stateMutability: "view",
    inputs: [],
    outputs: [
      { name: "value", type: "address" },
      { name: "validAt", type: "uint64" },
    ],
  },
  {
    type: "function",
    name: "pendingOwner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "isAllocator",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    type: "function",
    name: "lastTotalAssets",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  // Additional read functions from client.ts
  {
    type: "function",
    name: "convertToAssets",
    stateMutability: "view",
    inputs: [{ name: "shares", type: "uint256" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "performanceFeeBps",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint16" }],
  },
  {
    type: "function",
    name: "lastHarvest",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },

  // ===== Write Functions =====
  {
    type: "function",
    name: "reallocate",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "allocations",
        type: "tuple[]",
        components: [
          {
            name: "marketParams",
            type: "tuple",
            components: [
              { name: "loanToken", type: "address" },
              { name: "collateralToken", type: "address" },
              { name: "oracle", type: "address" },
              { name: "irm", type: "address" },
              { name: "lltv", type: "uint256" },
            ],
          },
          { name: "assets", type: "uint256" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "submitCap",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "marketParams",
        type: "tuple",
        components: [
          { name: "loanToken", type: "address" },
          { name: "collateralToken", type: "address" },
          { name: "oracle", type: "address" },
          { name: "irm", type: "address" },
          { name: "lltv", type: "uint256" },
        ],
      },
      { name: "newSupplyCap", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "acceptCap",
    stateMutability: "nonpayable",
    inputs: [
      {
        name: "marketParams",
        type: "tuple",
        components: [
          { name: "loanToken", type: "address" },
          { name: "collateralToken", type: "address" },
          { name: "oracle", type: "address" },
          { name: "irm", type: "address" },
          { name: "lltv", type: "uint256" },
        ],
      },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setSupplyQueue",
    stateMutability: "nonpayable",
    inputs: [{ name: "newSupplyQueue", type: "bytes32[]" }],
    outputs: [],
  },
  {
    type: "function",
    name: "updateWithdrawQueue",
    stateMutability: "nonpayable",
    inputs: [{ name: "indexes", type: "uint256[]" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setIsAllocator",
    stateMutability: "nonpayable",
    inputs: [
      { name: "newAllocator", type: "address" },
      { name: "newIsAllocator", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setFee",
    stateMutability: "nonpayable",
    inputs: [{ name: "newFee", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setFeeRecipient",
    stateMutability: "nonpayable",
    inputs: [{ name: "newFeeRecipient", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "submitTimelock",
    stateMutability: "nonpayable",
    inputs: [{ name: "newTimelock", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "acceptTimelock",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "submitGuardian",
    stateMutability: "nonpayable",
    inputs: [{ name: "newGuardian", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "acceptGuardian",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "setCurator",
    stateMutability: "nonpayable",
    inputs: [{ name: "newCurator", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "transferOwnership",
    stateMutability: "nonpayable",
    inputs: [{ name: "newOwner", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "renounceOwnership",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "submitOwner",
    stateMutability: "nonpayable",
    inputs: [{ name: "newOwner", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "acceptOwner",
    stateMutability: "nonpayable",
    inputs: [],
    outputs: [],
  },
  {
    type: "function",
    name: "skim",
    stateMutability: "nonpayable",
    inputs: [{ name: "token", type: "address" }],
    outputs: [],
  },
] as const;

export const vaultV2Abi = [
  // ===== Read Functions =====
  {
    type: "function",
    name: "owner",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "curator",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "timelock",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "totalAssets",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "performanceFee",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "managementFee",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "allocation",
    stateMutability: "view",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "absoluteCap",
    stateMutability: "view",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "relativeCap",
    stateMutability: "view",
    inputs: [{ name: "id", type: "bytes32" }],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "name",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "symbol",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "string" }],
  },
  {
    type: "function",
    name: "totalSupply",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "asset",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "address" }],
  },
  {
    type: "function",
    name: "maxRate",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    type: "function",
    name: "isSentinel",
    stateMutability: "view",
    inputs: [{ name: "account", type: "address" }],
    outputs: [{ name: "", type: "bool" }],
  },

  // ===== Write Functions =====
  {
    type: "function",
    name: "allocate",
    stateMutability: "nonpayable",
    inputs: [
      { name: "adapter", type: "address" },
      { name: "data", type: "bytes" },
      { name: "assets", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "deallocate",
    stateMutability: "nonpayable",
    inputs: [
      { name: "adapter", type: "address" },
      { name: "data", type: "bytes" },
      { name: "assets", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "increaseAbsoluteCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "idData", type: "bytes" },
      { name: "newAbsoluteCap", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "decreaseAbsoluteCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "idData", type: "bytes" },
      { name: "newAbsoluteCap", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "increaseRelativeCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "idData", type: "bytes" },
      { name: "newRelativeCap", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "decreaseRelativeCap",
    stateMutability: "nonpayable",
    inputs: [
      { name: "idData", type: "bytes" },
      { name: "newRelativeCap", type: "uint256" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "addAdapter",
    stateMutability: "nonpayable",
    inputs: [{ name: "adapter", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "removeAdapter",
    stateMutability: "nonpayable",
    inputs: [{ name: "adapter", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setPerformanceFee",
    stateMutability: "nonpayable",
    inputs: [{ name: "newFee", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setManagementFee",
    stateMutability: "nonpayable",
    inputs: [{ name: "newFee", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setMaxRate",
    stateMutability: "nonpayable",
    inputs: [{ name: "newMaxRate", type: "uint256" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setLiquidityAdapterAndData",
    stateMutability: "nonpayable",
    inputs: [
      { name: "liquidityAdapter", type: "address" },
      { name: "liquidityData", type: "bytes" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "submit",
    stateMutability: "nonpayable",
    inputs: [{ name: "data", type: "bytes" }],
    outputs: [],
  },
  {
    type: "function",
    name: "revoke",
    stateMutability: "nonpayable",
    inputs: [{ name: "data", type: "bytes" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setOwner",
    stateMutability: "nonpayable",
    inputs: [{ name: "newOwner", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setCurator",
    stateMutability: "nonpayable",
    inputs: [{ name: "newCurator", type: "address" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setIsSentinel",
    stateMutability: "nonpayable",
    inputs: [
      { name: "account", type: "address" },
      { name: "newIsSentinel", type: "bool" },
    ],
    outputs: [],
  },
  {
    type: "function",
    name: "setName",
    stateMutability: "nonpayable",
    inputs: [{ name: "newName", type: "string" }],
    outputs: [],
  },
  {
    type: "function",
    name: "setSymbol",
    stateMutability: "nonpayable",
    inputs: [{ name: "newSymbol", type: "string" }],
    outputs: [],
  },
  {
    type: "function",
    name: "multicall",
    stateMutability: "nonpayable",
    inputs: [{ name: "data", type: "bytes[]" }],
    outputs: [],
  },
] as const;
